// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UcmData.Client.Data;

#nullable disable

namespace UcmData.Client.Migrations
{
    [DbContext(typeof(DbContextUcm))]
    partial class DbContextUcmModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UcmData.Client.Models.cdr", b =>
                {
                    b.Property<int>("AcctId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcctId"), 1L, 1);

                    b.Property<string>("accountcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("answer")
                        .HasColumnType("datetime2");

                    b.Property<int>("billsec")
                        .HasColumnType("int");

                    b.Property<string>("clid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dstchannel_ext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("end")
                        .HasColumnType("datetime2");

                    b.Property<string>("src")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("src_trunk_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start")
                        .HasColumnType("datetime2");

                    b.HasKey("AcctId");

                    b.ToTable("cdrs");
                });
#pragma warning restore 612, 618
        }
    }
}
